In [8]:
import pandas as pd 
import numpy as np                                                                                              
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
# from sklearn.preprocessing import OneHotEncoder

In [9]:
##Basic setting , read data, clean and convert date time
df = pd.read_csv('data.csv', header=1)
df['Date'] = pd.to_datetime(df['Date'])
df = df.dropna()

In [10]:
# ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform='pandas')
le = LabelEncoder()

In [11]:
df = df.sort_values(by=['Individual code', 'Date'])
df

,Year,Date,Month,Day of Week,Individual code,0,1,2,3,4,...,15,16,17,18,19,20,21,22,23,Daily total (Wh/d)
3178,2013,2013-09-06,9,Friday,F2013_10_B,0.0,5.0,3.0,0.0,0.0,...,0.0,0.0,0.0,2.0,0.0,0.0,18.0,44.0,15.0,87.0
3171,2013,2013-09-07,9,Saturday,F2013_10_B,0.0,5.0,9.0,16.0,28.0,...,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,104.0
3188,2013,2013-09-08,9,Sunday,F2013_10_B,1.0,0.0,0.0,13.0,11.0,...,0.0,1.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,55.0
3176,2013,2013-09-09,9,Monday,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0
3185,2013,2013-09-10,9,Tuesday,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,2019,2019-12-09,12,Monday,F2019_9_D,27.0,35.0,31.0,29.0,29.0,...,0.0,0.0,3.0,20.0,0.0,0.0,0.0,0.0,10.0,403.0
29439,2019,2019-12-10,12,Tuesday,F2019_9_D,44.0,36.0,31.0,32.0,33.0,...,12.0,4.0,0.0,0.0,1.0,0.0,0.0,31.0,31.0,398.0
29440,2019,2019-12-11,12,Wednesday,F2019_9_D,24.0,35.0,49.0,29.0,26.0,...,0.0,0.0,37.0,29.0,27.0,26.0,20.0,19.0,101.0,556.0
29441,2019,2019-12-12,12,Thursday,F2019_9_D,54.0,38.0,26.0,27.0,27.0,...,8.0,29.0,34.0,31.0,37.0,28.0,58.0,28.0,0.0,608.0
29442,2019,2019-12-13,12,Friday,F2019_9_D,0.0,54.0,37.0,30.0,31.0,...,0.0,66.0,31.0,41.0,21.0,14.0,0.0,0.0,0.0,513.0

In [12]:
#Seperate dataset from different individuals 
df_filtered = df
hour_cols = [str(i) for i in range(24)]
df_filtered[["Lag1_"+ col for col in hour_cols]] = (df_filtered.groupby("Individual code")[hour_cols].shift(1)) ## Add time lag features + NA for first day of each individual

df_filtered["Lag1_Total"] = df.groupby("Individual code")["Daily total (Wh/d)"].shift(1)
df_filtered

,Year,Date,Month,Day of Week,Individual code,0,1,2,3,4,...,Lag1_15,Lag1_16,Lag1_17,Lag1_18,Lag1_19,Lag1_20,Lag1_21,Lag1_22,Lag1_23,Lag1_Total
3178,2013,2013-09-06,9,Friday,F2013_10_B,0.0,5.0,3.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3171,2013,2013-09-07,9,Saturday,F2013_10_B,0.0,5.0,9.0,16.0,28.0,...,0.0,0.0,0.0,2.0,0.0,0.0,18.0,44.0,15.0,87.0
3188,2013,2013-09-08,9,Sunday,F2013_10_B,1.0,0.0,0.0,13.0,11.0,...,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,104.0
3176,2013,2013-09-09,9,Monday,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,55.0
3185,2013,2013-09-10,9,Tuesday,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,2019,2019-12-09,12,Monday,F2019_9_D,27.0,35.0,31.0,29.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,39.0,153.0,207.0
29439,2019,2019-12-10,12,Tuesday,F2019_9_D,44.0,36.0,31.0,32.0,33.0,...,0.0,0.0,3.0,20.0,0.0,0.0,0.0,0.0,10.0,403.0
29440,2019,2019-12-11,12,Wednesday,F2019_9_D,24.0,35.0,49.0,29.0,26.0,...,12.0,4.0,0.0,0.0,1.0,0.0,0.0,31.0,31.0,398.0
29441,2019,2019-12-12,12,Thursday,F2019_9_D,54.0,38.0,26.0,27.0,27.0,...,0.0,0.0,37.0,29.0,27.0,26.0,20.0,19.0,101.0,556.0
29442,2019,2019-12-13,12,Friday,F2019_9_D,0.0,54.0,37.0,30.0,31.0,...,8.0,29.0,34.0,31.0,37.0,28.0,58.0,28.0,0.0,608.0

In [13]:
df_filtered = df_filtered.dropna() # Drop NA rows (first day of each individual )
# Convert month and day of week to numerical values
df_filtered['Day of Week'] = pd.to_datetime(df_filtered['Date']).dt.dayofweek
df_filtered['Month'] = pd.to_datetime(df_filtered['Date']).dt.month
df_filtered

C:\Users\Admin\AppData\Local\Temp\ipykernel_34124\3563649201.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Day of Week'] = pd.to_datetime(df_filtered['Date']).dt.dayofweek
C:\Users\Admin\AppData\Local\Temp\ipykernel_34124\3563649201.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Month'] = pd.to_datetime(df_filtered['Date']).dt.month

,Year,Date,Month,Day of Week,Individual code,0,1,2,3,4,...,Lag1_15,Lag1_16,Lag1_17,Lag1_18,Lag1_19,Lag1_20,Lag1_21,Lag1_22,Lag1_23,Lag1_Total
3171,2013,2013-09-07,9,5,F2013_10_B,0.0,5.0,9.0,16.0,28.0,...,0.0,0.0,0.0,2.0,0.0,0.0,18.0,44.0,15.0,87.0
3188,2013,2013-09-08,9,6,F2013_10_B,1.0,0.0,0.0,13.0,11.0,...,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,104.0
3176,2013,2013-09-09,9,0,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,55.0
3185,2013,2013-09-10,9,1,F2013_10_B,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0
3157,2013,2013-09-11,9,2,F2013_10_B,32.0,13.0,13.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,2019,2019-12-09,12,0,F2019_9_D,27.0,35.0,31.0,29.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,39.0,153.0,207.0
29439,2019,2019-12-10,12,1,F2019_9_D,44.0,36.0,31.0,32.0,33.0,...,0.0,0.0,3.0,20.0,0.0,0.0,0.0,0.0,10.0,403.0
29440,2019,2019-12-11,12,2,F2019_9_D,24.0,35.0,49.0,29.0,26.0,...,12.0,4.0,0.0,0.0,1.0,0.0,0.0,31.0,31.0,398.0
29441,2019,2019-12-12,12,3,F2019_9_D,54.0,38.0,26.0,27.0,27.0,...,0.0,0.0,37.0,29.0,27.0,26.0,20.0,19.0,101.0,556.0
29442,2019,2019-12-13,12,4,F2019_9_D,0.0,54.0,37.0,30.0,31.0,...,8.0,29.0,34.0,31.0,37.0,28.0,58.0,28.0,0.0,608.0

In [14]:
df_filtered["Individual code"] = le.fit_transform(df_filtered["Individual code"]) # Convert Individual code to numerical values
df_filtered

C:\Users\Admin\AppData\Local\Temp\ipykernel_34124\3532911854.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered["Individual code"] = le.fit_transform(df_filtered["Individual code"]) # Convert Individual code to numerical values

,Year,Date,Month,Day of Week,Individual code,0,1,2,3,4,...,Lag1_15,Lag1_16,Lag1_17,Lag1_18,Lag1_19,Lag1_20,Lag1_21,Lag1_22,Lag1_23,Lag1_Total
3171,2013,2013-09-07,9,5,0,0.0,5.0,9.0,16.0,28.0,...,0.0,0.0,0.0,2.0,0.0,0.0,18.0,44.0,15.0,87.0
3188,2013,2013-09-08,9,6,0,1.0,0.0,0.0,13.0,11.0,...,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0,104.0
3176,2013,2013-09-09,9,0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0,55.0
3185,2013,2013-09-10,9,1,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88.0
3157,2013,2013-09-11,9,2,0,32.0,13.0,13.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,66.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,2019,2019-12-09,12,0,347,27.0,35.0,31.0,29.0,29.0,...,0.0,0.0,0.0,0.0,0.0,0.0,7.0,39.0,153.0,207.0
29439,2019,2019-12-10,12,1,347,44.0,36.0,31.0,32.0,33.0,...,0.0,0.0,3.0,20.0,0.0,0.0,0.0,0.0,10.0,403.0
29440,2019,2019-12-11,12,2,347,24.0,35.0,49.0,29.0,26.0,...,12.0,4.0,0.0,0.0,1.0,0.0,0.0,31.0,31.0,398.0
29441,2019,2019-12-12,12,3,347,54.0,38.0,26.0,27.0,27.0,...,0.0,0.0,37.0,29.0,27.0,26.0,20.0,19.0,101.0,556.0
29442,2019,2019-12-13,12,4,347,0.0,54.0,37.0,30.0,31.0,...,8.0,29.0,34.0,31.0,37.0,28.0,58.0,28.0,0.0,608.0

In [15]:
# Define input features and target variable
X_cols = [f"Lag1_{i}" for i in hour_cols] + ["Lag1_Total","Day of Week", "Month","Individual code"]
x = df_filtered[X_cols]
x

,Lag1_0,Lag1_1,Lag1_2,Lag1_3,Lag1_4,Lag1_5,Lag1_6,Lag1_7,Lag1_8,Lag1_9,...,Lag1_18,Lag1_19,Lag1_20,Lag1_21,Lag1_22,Lag1_23,Lag1_Total,Day of Week,Month,Individual code
3171,0.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,18.0,44.0,15.0,87.0,5,9,0
3188,0.0,5.0,9.0,16.0,28.0,35.0,4.0,0.0,0.0,0.0,...,0.0,5.0,1.0,0.0,0.0,0.0,104.0,6,9,0
3176,1.0,0.0,0.0,13.0,11.0,12.0,1.0,2.0,3.0,0.0,...,0.0,0.0,6.0,4.0,0.0,0.0,55.0,0,9,0
3185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,88.0,1,9,0
3157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,41.0,6.0,...,0.0,0.0,0.0,0.0,0.0,5.0,66.0,2,9,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,7.0,39.0,153.0,207.0,0,12,347
29439,27.0,35.0,31.0,29.0,29.0,30.0,29.0,29.0,29.0,28.0,...,20.0,0.0,0.0,0.0,0.0,10.0,403.0,1,12,347
29440,44.0,36.0,31.0,32.0,33.0,32.0,32.0,31.0,31.0,3.0,...,0.0,1.0,0.0,0.0,31.0,31.0,398.0,2,12,347
29441,24.0,35.0,49.0,29.0,26.0,26.0,25.0,26.0,25.0,6.0,...,29.0,27.0,26.0,20.0,19.0,101.0,556.0,3,12,347
29442,54.0,38.0,26.0,27.0,27.0,26.0,27.0,27.0,27.0,26.0,...,31.0,37.0,28.0,58.0,28.0,0.0,608.0,4,12,347

In [16]:
y = df_filtered[hour_cols]  # Predicting hourly consumption for the day
y

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
3171,0.0,5.0,9.0,16.0,28.0,35.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.0,1.0,0.0,0.0,0.0
3188,1.0,0.0,0.0,13.0,11.0,12.0,1.0,2.0,3.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,6.0,4.0,0.0,0.0
3176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3185,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,41.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3157,32.0,13.0,13.0,6.0,0.0,0.0,23.0,85.0,71.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29438,27.0,35.0,31.0,29.0,29.0,30.0,29.0,29.0,29.0,28.0,...,0.0,0.0,0.0,3.0,20.0,0.0,0.0,0.0,0.0,10.0
29439,44.0,36.0,31.0,32.0,33.0,32.0,32.0,31.0,31.0,3.0,...,8.0,12.0,4.0,0.0,0.0,1.0,0.0,0.0,31.0,31.0
29440,24.0,35.0,49.0,29.0,26.0,26.0,25.0,26.0,25.0,6.0,...,0.0,0.0,0.0,37.0,29.0,27.0,26.0,20.0,19.0,101.0
29441,54.0,38.0,26.0,27.0,27.0,26.0,27.0,27.0,27.0,26.0,...,21.0,8.0,29.0,34.0,31.0,37.0,28.0,58.0,28.0,0.0
29442,0.0,54.0,37.0,30.0,31.0,29.0,31.0,30.0,30.0,23.0,...,0.0,0.0,66.0,31.0,41.0,21.0,14.0,0.0,0.0,0.0